### ISSUE TITLE
Networking support issue

### ISSUE THREAD

**Issue by dawnofman** [humphd/browser-shell#6]
The [network support](https://github.com/copy/v86/blob/master/docs/archlinux.md#networking) doesn't work as the module 'ne2k-pci' module is not available. I have checked the defconfig of browser-vm to see dhcp and module are enabled. Did you trim down networking support? Or do you suggestion for networking support with extension of browser-shell?

**Comment by humphd** [comment]
The VM I build to run Linux strips out almost all of the networking stack, since I didn't need it, and wanted to save space.  You could use my scripts in https://github.com/humphd/browser-vm to configure a VM that includes it if you wanted to add it back.

**Comment by tennox** [comment]
@dawnofman did you figure out how to do that?
Would love to have a browser-vm with networking support :thinking:
