### ISSUE TITLE
How can I start this cool project?

### ISSUE THREAD

**Issue by jtuttas** [humphd/browser-shell#8]

**Comment by Prince-Mendiratta** [comment]
some help with this please, @humphd ?

**Comment by humphd** [comment]
I don't understand the question, it's a web site: https://humphd.github.io/browser-shell/

**Comment by Prince-Mendiratta** [comment]
Ah, what I was trying to ask was how can I run this on my localhost? I've tried the following steps but they don't seem to work -

```
npm install
npm run build
./tools/download-binaries.sh v1.0.2
npx parcel dist/index.html
```

**Comment by humphd** [comment]
What error do you get?  I haven't tried to set this up in a long time, it's likely dependency issues.

**Comment by Prince-Mendiratta** [comment]
I managed to get it running in a development environment, without building it using the following steps -
```
npm install
./tools/download-binaries.sh v1.0.2
npx parcel src/index.html
```

As for the production build I get the following error -
![image](https://user-images.githubusercontent.com/54077356/159980507-fdebe26d-772e-4ca7-9c20-1d1ac73d9891.png)

**Comment by humphd** [comment]
`npm run build` works for me on Mac.  I suspect that `npx` is going to give you a newer Parcel than I used, so things will break.

I'm not maintaining this, so I suspect a bunch of things I used need to get updated and tweaked.

**Comment by Prince-Mendiratta** [comment]
Understood, thank you so much for your efforts, this project is awesome!

**Comment by humphd** [comment]
Thanks! Sorry I can't be more useful.  What I know about this project is all there in the code, I haven't had time to look at any of it again since I published it.  If you can do something with it, that would be great.  Good luck.
